baseURL = "https://looped.network/"
languageCode = "en-us"
title = "LoopedNetwork"

theme = "hugo-ficurinia"

author = "LoopedNetwork"
copyright = "Copyright 2023 - LoopedNetwork"

paginate = 10
summaryLength = 70

[params]
mainSections = ["2022", "2023"]
    description = "The /dev/null of my life."
    author = "LoopedNetwork"
    logo = "/logo.svg"
    faviconIco = "/favicon.ico"

    enableShareOnFediverse = false

    imageInArticlePreview = false
    enableRelatedArticles = false
    forceRedirect = true

    fontFamily = "JetBrains Mono"
    titleFontFamily = "JetBrains Mono"
    monospaceFontFamily = "JetBrains Mono"

    titleFontSizeMultiplier = 1.0
    mainFontSizeMultiplier = 1.0
    monoFontSizeMultiplier = 1.0

    contentWidth = "1000px"

    tagsInArticlePreview = true
    gridView = false
    bigArticleTitle = false
    navtype = "standard"
    enableShadow = false
    menuStyle = "standard"
    enableSearch = true
    searchbarEverywhere = true
    searchMenuLink = false
    mobileHamburgerNav = false
    enableFeatured = false
    underlineTitleLinks = false
    tocBeforeImage = false

    enableSidebarLayout = false
    tocInSidebar = false

    infiniteScrolling = false
    enableFooterColumns = false
    enableJumbotron = false

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    [[menu.icons]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/jfabry-noc"
        weight = 10
    [[menu.icons]]
        identifier = "mastodon"
        name = "Mastodon"
        url = "https://social.sdf.org/@loopednetwork"
        weight = 20

